apiVersion: apps/v1
kind: Deployment
metadata:
  name: tika
  labels:
    app.kubernetes.io/name: tika
spec:
  selector:
    matchLabels:
      app: tika
  template:
    metadata:
      labels:
        app: tika
    spec:
      containers:
        - name: tika
          image: "apache/tika:2.9.2.1-full"
          ports:
            - containerPort: 9998
