# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: keycloak-operator
iconUrl: https://avatars.githubusercontent.com/u/4921466
shortDescription: Open Source Identity and Access Management
longDescription: |
  Add authentication to applications and secure services with minimum effort.
  No need to deal with storing users or authenticating users.
  Keycloak provides user federation, strong authentication, user management, fine-grained authorization, and more.
defaultNamespace: keycloak
scope: Namespaced
dependencies:
  - name: "keycloak-operator-crds"
manifests:
  - url: ./manifest.yaml
