# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json
name: knative-eventing
shortDescription: Event-driven application platform for Kubernetes
longDescription: |
  Knative Eventing is a collection of APIs that enable you to use an event-driven architecture with your applications. You can use these APIs to create components that route events from event producers (known as sources) to event consumers (known as sinks) that receive events. Sinks can also be configured to respond to HTTP requests by sending a response event.

  Knative Eventing is a standalone platform that provides support for various types of workloads, including standard Kubernetes Services and Knative Serving Services.

  Knative Eventing uses standard HTTP requests to route events from event producers to event consumers, following the rules set by the CloudEvents specification. This is a standard set up by the CNCF that has wide support for many programming languages, making it easy to create, understand, send, and receive events.

  Knative Eventing components are loosely coupled, and can be developed and deployed independently of each other. Any producer can generate events before there are active event consumers that are listening for those events. Any event consumer can express interest in a class of events before there are producers that are creating those events.
iconUrl: https://raw.githubusercontent.com/knative/docs/e1286025fc19330b7f5d9aa26cc364899992f8e3/blog/docs/images/knative.png
defaultNamespace: knative-eventing
manifests:
  - url: https://github.com/knative/eventing/releases/download/knative-v1.10.1/eventing-crds.yaml
  - url: https://github.com/knative/eventing/releases/download/knative-v1.10.1/eventing-core.yaml
