# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: argo-cd
shortDescription: Declarative Continuous Deployment for Kubernetes
defaultNamespace: argocd
iconUrl: https://avatars.githubusercontent.com/u/30269780
manifests:
  - url: https://raw.githubusercontent.com/argoproj/argo-cd/v3.1.1/manifests/install.yaml
entrypoints:
  - serviceName: argocd-server
    port: 443
    localPort: 8082
    scheme: https
