# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: keycloak-operator-crds
iconUrl: https://avatars.githubusercontent.com/u/4921466
shortDescription: Open Source Identity and Access Management
longDescription: |
  **Note:** this package only contains the CRDs
  
  Add authentication to applications and secure services with minimum effort.
  No need to deal with storing users or authenticating users.
  Keycloak provides user federation, strong authentication, user management, fine-grained authorization, and more.
defaultNamespace: default
scope: Cluster
manifests:
  - url: https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.2/kubernetes/keycloaks.k8s.keycloak.org-v1.yml
  - url: https://raw.githubusercontent.com/keycloak/keycloak-k8s-resources/25.0.2/kubernetes/keycloakrealmimports.k8s.keycloak.org-v1.yml
