apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16.4
  bootstrap:
    initdb: {}
  storage: {}
  monitoring:
    enablePodMonitor: true
  resources:
    limits:
      memory: 256Mi
    requests:
      cpu: 10m
      memory: 256Mi
