apiVersion: "kustomize.config.k8s.io/v1beta1"
kind: "Kustomization"
namespace: keptn-system

resources:
  - template.yaml

patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: lifecycle-operator
      namespace: keptn-system
    path: patch.yaml
