# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json
name: glasskube-autoupdater
defaultNamespace: glasskube-system
scope: Cluster
shortDescription: Opt-in to automatic updates for your Packages
manifests:
  - url: https://github.com/glasskube/glasskube/releases/download/v0.14.0/manifest-autoupdater.yaml
references:
  - label: GitHub
    url: https://github.com/glasskube/glasskube
valueDefinitions:
  schedule:
    type: text
    defaultValue: "0 0 * * *"
    metadata:
      description: CronJob schedule for automatic updates
    targets:
      - patch:
          op: add
          path: /spec/schedule
        resource:
          apiGroup: batch/v1
          kind: CronJob
          name: glasskube-autoupdate
