# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: k8sgpt-operator
iconUrl: https://avatars.githubusercontent.com/u/128535266?s=150
shortDescription: Automatic SRE Superpowers within your Kubernetes cluster
longDescription: Automatic SRE Superpowers within your Kubernetes cluster
defaultNamespace: k8sgpt-operator-system
helm:
  chartName: k8sgpt-operator
  chartVersion: 0.2.24
  repositoryUrl: https://charts.k8sgpt.ai
references:
  - label: ArtifactHub
    url: https://artifacthub.io/packages/helm/k8sgpt/k8sgpt-operator
manifests:
  - url: https://glasskube.github.io/packages/packages/k8sgpt-operator/v0.2.24+1/manifest.yaml
valueDefinitions:
  openaiApiKey:
    type: text
    targets:
      - patch:
          op: add
          path: /data/openai-api-key
        valueTemplate: |
          "{{ . | base64 }}"
        resource:
          apiGroup: v1
          kind: Secret
          name: k8sgpt-secret
          namespace: k8sgpt-operator-system
    constraints:
      required: true
      minLength: 50
      pattern: sk-.+
  anonymized:
    type: boolean
    defaultValue: "false"
    targets:
      - patch:
          op: add
          path: /spec/ai/anonymized
        valueTemplate: "{{ . }}"
        resource:
          apiGroup: core.k8sgpt.ai/v1alpha1
          kind: K8sGPT
          name: k8sgpt
          namespace: k8sgpt-operator-system
  language:
    type: text
    defaultValue: english
    targets:
      - patch:
          op: add
          path: /spec/ai/language
        resource:
          apiGroup: core.k8sgpt.ai/v1alpha1
          kind: K8sGPT
          name: k8sgpt
          namespace: k8sgpt-operator-system
