# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json
name: temporal
scope: Namespaced
defaultNamespace: default
manifests:
  - url: ./db.yaml
helm:
  repositoryUrl: https://go.temporal.io/helm-charts
  chartName: temporal
  chartVersion: "0.44.0"
  values:
    server:
      config:
        persistence:
          default:
            driver: "sql"
            sql:
              driver: "postgres12"
              host: temporal-db-rw
              port: 5432
              database: temporal
              user: postgres
              existingSecret: temporal-db-superuser
              maxConns: 20
              maxConnLifetime: "1h"
          visibility:
            driver: "sql"
            sql:
              driver: "postgres12"
              host: temporal-db-rw
              port: 5432
              database: temporal_visibility
              user: postgres
              existingSecret: temporal-db-superuser
              maxConns: 20
              maxConnLifetime: "1h"
    cassandra:
      enabled: false
    mysql:
      enabled: false
    postgresql:
      enabled: true
    prometheus:
      enabled: false
    grafana:
      enabled: false
    elasticsearch:
      enabled: false
    schema:
      createDatabase:
        enabled: true
      setup:
        enabled: true
      update:
        enabled: true
dependencies:
  - name: cloudnative-pg
transformations:
  - source:
      path: "{ $.metadata.name }"
    targets:
      - chartName: temporal
        valueTemplate: '"{{.}}-db-superuser"'
        patch:
          op: add
          path: /server/config/persistence/default/sql/existingSecret
      - chartName: temporal
        valueTemplate: '"{{.}}-db-superuser"'
        patch:
          op: add
          path: /server/config/persistence/visibility/sql/existingSecret
      - chartName: temporal
        valueTemplate: '"{{.}}-db-rw"'
        patch:
          op: add
          path: /server/config/persistence/default/sql/host
      - chartName: temporal
        valueTemplate: '"{{.}}-db-rw"'
        patch:
          op: add
          path: /server/config/persistence/visibility/sql/host
references:
  - label: Website
    url: https://temporal.io/
entrypoints:
  - serviceName: temporal-web
    port: 8080
