# yaml-language-server: $schema=../schema.json

name: "cert-manager"
shortDescription: >-
  cert-manager adds certificates and certificate issuers as resource types in Kubernetes clusters,
  and simplifies the process of obtaining, renewing and using those certificates.
defaultNamespace: "cert-manager"
helm:
  repositoryUrl: "https://charts.jetstack.io"
  chartName: "cert-manager"
  chartVersion: "v1.13.3"
  values:
    installCRDs: "true"
