# yaml-language-server: $schema=https://glasskube.dev/schemas/v1/package-manifest.json

name: "cert-manager"
shortDescription: >-
  cert-manager adds certificates and certificate issuers as resource types in Kubernetes clusters,
  and simplifies the process of obtaining, renewing and using those certificates.
iconUrl: "https://avatars.githubusercontent.com/u/39950598"
defaultNamespace: "cert-manager"
helm:
  repositoryUrl: "https://charts.jetstack.io"
  chartName: "cert-manager"
  chartVersion: "v1.13.3"
  values:
    installCRDs: "true"
