name: Auto-merge package updates
on: pull_request

permissions:
  pull-requests: write

jobs:
  automerge:
    runs-on: ubuntu-latest
    if: "github.actor == 'glasskube-bot' && startsWith(github.event.pull_request.title, 'chore: update package ')"
    steps:
      - name: Enable Pull Request Automerge
        run: gh pr merge --squash --auto
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
