name: Update index.yaml

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Generate index.yaml
        uses: mikefarah/yq@dd648994340a5d03225d97abf19c9bf1086c3f07 # v4.40.5
        with:
          cmd: yq ea '{"name":.name, "shortDescription":.shortDescription, "iconUrl":.iconUrl}' packages/*/package.yaml | yq '[.]' | yq '{"packages":.}' > packages/index.yaml
      - name: Generate and push index.yaml
        run: |
          git config user.name 'glasskube-bot'
          git config user.email 'githubbot@glasskube.eu'
          git add packages/index.yaml
          git commit -m "chore: update packages/index.yaml"
          git branch -D bot/package-index-update || true
          git checkout -b bot/package-index-update
          git push --force --set-upstream origin bot/package-index-update || true
      - name: Create pull request if it not yet exists
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh pr create --fill || true
