name: Update index.yaml

on:
  push:
    branches:
      - main

permissions:
  pull-requests: write
  contents: write

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          fetch-depth: 0
      - name: Generate index.yaml
        uses: mikefarah/yq@bb66c9c872a7a4cf3d6846c2ff6d182c66ec3f77 # v4.40.7
        with:
          cmd: yq ea '{"name":.name, "shortDescription":.shortDescription, "iconUrl":.iconUrl}' packages/*/package.yaml | yq '[.]' | yq '{"packages":.}' > packages/index.yaml
      - name: Create or update pull request
        uses: peter-evans/create-pull-request@b1ddad2c994a25fbc81a28b3ec0e368bb2021c50 # v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          committer: "glasskube-bot <githubbot@glasskube.eu>"
          signoff: true
          branch: "bot/package-index-update"
          commit-message: "chore: update packages/index.yaml"
          title: "chore: update packages/index.yaml"
          body: |
            :robot: Automated PR
            ---
            Merge this PR to update `packages/index.yaml`.
